#!/bin/bash

path=$(realpath $1)

echo > /sys/kernel/config/usb_gadget/g1/UDC
rm /sys/kernel/config/usb_gadget/g1/configs/c.1/hid.foo
rmdir /sys/kernel/config/usb_gadget/g1/functions/hid.foo
rmdir /sys/kernel/config/usb_gadget/g1/configs/c.1/strings/0x409
rmdir /sys/kernel/config/usb_gadget/g1/configs/c.1
rmdir /sys/kernel/config/usb_gadget/g1/strings/0x409
rmdir /sys/kernel/config/usb_gadget/g1

modprobe usb_f_hid

cd /sys/kernel/config/usb_gadget
mkdir g1
cd g1
mkdir functions/hid.foo
cd functions/hid.foo

  echo 1 > protocol
  echo 1 > subclass
  echo 13 > report_length
  cat "$path" > report_desc
cd ../..

mkdir -pv configs/c.1/strings/0x409
echo "keyboard mode" > configs/c.1/strings/0x409/configuration

mkdir strings/0x409
echo "cleverca22" > strings/0x409/manufacturer
echo "rpi-tools pi400 keyboard" > strings/0x409/product
grep Serial /proc/cpuinfo  | cut -c19-26 > strings/0x409/serialnumber

ln -sv functions/hid.foo configs/c.1

ls /sys/class/udc/ > UDC
