#!/bin/bash


echo > /sys/kernel/config/usb_gadget/g1/UDC
rm /sys/kernel/config/usb_gadget/g1/configs/c.1/hid.foo
rm /sys/kernel/config/usb_gadget/g1/configs/c.1/mass_storage.foo
rmdir /sys/kernel/config/usb_gadget/g1/functions/mass_storage.foo
rmdir /sys/kernel/config/usb_gadget/g1/functions/hid.foo
rmdir /sys/kernel/config/usb_gadget/g1/configs/c.1/strings/0x409
rmdir /sys/kernel/config/usb_gadget/g1/configs/c.1
rmdir /sys/kernel/config/usb_gadget/g1/strings/0x409
rmdir /sys/kernel/config/usb_gadget/g1/strings/0x411
rmdir /sys/kernel/config/usb_gadget/g1

modprobe usb_f_hid

set -e

cd /sys/kernel/config/usb_gadget
mkdir g1
cd g1
mkdir functions/mass_storage.foo
cd functions/mass_storage.foo
  echo '/nas/downloads/SnowLeopardInstall/snow leopard install.iso' > lun.0/file
cd ../..

mkdir -pv configs/c.1/strings/0x409
echo "msd mode" > configs/c.1/strings/0x409/configuration

mkdir strings/0x409
mkdir strings/0x411
echo "cleverca22" > strings/0x409/manufacturer
echo "rpi-tools pi400 keyboard" > strings/0x409/product
echo "テスト" > strings/0x411/product
grep Serial /proc/cpuinfo  | cut -c19-26 > strings/0x409/serialnumber

ln -sv functions/mass_storage.foo configs/c.1

ls /sys/class/udc/ > UDC
